name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.4-slim

    steps:
    - uses: actions/checkout@v1

    # - uses: actions/cache@v1
    #   id: cache
    #   with:
    #     path: deps
    #     key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
    #     restore-keys: |
    #       ${{ runner.os }}-mix-

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix do deps.get, deps.compile, compile

    - name: Lint Check
      run: mix credo --strict

    - name: Type Check
      run: mix dialyzer --format short --halt-exit-status

    - name: Run Tests
      run: mix test
